Repository nyu-software-engineering/drawing-with-friends, pull requests merged in 2019-04, with the labels that each got.

#80 79/update front page
  frontend/src/components/Footer.jsx
  frontend/src/components/Homepage/AboutUs.jsx
  frontend/src/components/Homepage/Greeting.jsx
  frontend/src/components/Homepage/Homepage.jsx
  frontend/src/components/Homepage/Instructions.jsx
  frontend/src/css/AboutUs.css
  frontend/src/css/Greeting.css
  frontend/src/css/Homepage.css
  frontend/src/css/Instructions.css
  frontend/src/index.jsx
  frontend/test/components/Footer.spec.jsx
Labels: Task

#82 Add image loader to webpack configuration
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Canvas/CanvasWrapper.jsx
  frontend/src/components/Canvas/DrawingCanvas.js
  frontend/src/components/Homepage/AboutUs.jsx
  frontend/src/components/Homepage/Greeting.jsx
  frontend/src/images/pencil.svg
  frontend/webpack.config.js
  package-lock.json
  package.json
Labels: Spike

#84 83/fix canvas
  frontend/src/components/Canvas/DrawingCanvas.js
  frontend/src/images/Circle.png
  frontend/src/images/Eraser.png
  frontend/src/images/Large.png
  frontend/src/images/Medium.png
  frontend/src/images/Small.png
  frontend/src/images/Square.png
Labels: Bug, Spike

#86 85/allow page refreshing
  frontend/src/components/Canvas/DrawingCanvas.js
  netlify.toml
Labels: Task

#92 89/game page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AboutUs.jsx
  frontend/src/components/Canvas/DrawingCanvas.js
  frontend/src/components/GamePage.jsx
  frontend/src/components/Homepage/AboutUs.jsx
  frontend/src/components/Homepage/Greeting.jsx
  frontend/src/components/Homepage/Instructions.jsx
  frontend/src/css/AboutUs.css
  frontend/src/css/GamePage.css
  frontend/src/css/Greeting.css
  frontend/src/css/Instructions.css
  frontend/src/images/InstructionsLogo.svg
  frontend/src/images/PencilsIcon.svg
  frontend/src/images/Rocket.svg
  frontend/src/index.jsx
  frontend/test/routes/AboutUs.spec.jsx
Labels: Task

#94 Sync erase all on canvas
  backend/src/app.js
  frontend/src/components/Canvas/DrawingCanvas.js
Labels: Task

#95 88/join game page
  frontend/src/components/JoinGamePage.jsx
  frontend/src/components/NavigationBar.jsx
  frontend/src/css/JoinGamePage.css
  frontend/src/index.jsx
  frontend/test/components/NavigationBar.spec.jsx
Labels: Task

#97 Render chat messages
  frontend/src/components/GamePage.jsx
Labels: Task

#99 Added setting
  frontend/src/components/Setting.jsx
Labels: Task

#100 87/create game page
  frontend/src/components/CreateGamePage.jsx
  frontend/src/components/NavigationBar.jsx
  frontend/src/css/CreateGamePage.css
  frontend/src/index.jsx
  frontend/test/components/NavigationBar.spec.jsx
Labels: Task

#101 Implement rooms and chat
  backend/src/app.js
  backend/src/room.js
  frontend/.eslintrc
  frontend/package.json
  frontend/src/components/Canvas/DrawingCanvas.js
  frontend/src/components/Chat.jsx
  frontend/src/components/CreateGamePage.jsx
  frontend/src/components/GamePage.jsx
  frontend/src/components/JoinGamePage.jsx
  frontend/src/index.jsx
  frontend/src/utils/SocketConnect.js
Labels: Task

#103 Sync canvas based on room. Fix dependency vulnerabilities
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Canvas/CanvasWrapper.jsx
  frontend/src/components/Canvas/DrawingCanvas.js
Labels: Task

#105 104/site fixup
  frontend/src/components/Chat.jsx
  frontend/src/components/CreateGamePage.jsx
  frontend/src/components/GamePage.jsx
  frontend/src/css/CreateGamePage.css
  frontend/src/css/GamePage.css
  frontend/src/css/JoinGamePage.css
Labels: Task
